{
  pkgs,
  # config,
  # lib,
  # myvars,
  ...
}: {
  imports = [
    # base modules for any system
    ../base

    # modules for NixOS system
    ./base
    ./desktop
    ./gui
    ./theme
  ];

  config = {
    # Enabling custom system modules
    modules = {
      nh = {
        enable = true;
        numOfGens = "5";
        timeRange = "3d";
      };
      theme = {
        fonts = {
          enable = true;
          # extraFontsPkgs = with pkgs; [];
        };
        stylix.enable = true;
        polarity = "dark";
        colorScheme = "kanagawa-dragon";
      };
      desktop = {
        gaming.enable = true;
        peripherals = {
          audio.enable = true;
          bluetooth.enable = true;
          # printing.enable = true;
        };
      };
      gui = {
        wm = {
          # niri.enable = true;
          # mangowc.enable = true; # with tuigreet
          hypr.enable = true; # with tuigreet
          # gnome.enable = true;
          # cosmic.enable = true;
          # plasma.enable = true;
        };
      };
    };

    hardware.i2c.enable = true;
    environment.systemPackages = with pkgs; [
      ddcutil
    ];
  };

  # config = lib.mkMerge [
  #   (lib.mkIf cfgWayland.enable {
  #     ####################################################################
  #     #  NixOS's Configuration for Wayland based Window Manager
  #     ####################################################################
  #     services = {
  #       xserver.enable = false; # disable xorg server
  #       # https://wiki.archlinux.org/title/Greetd
  #       greetd = {
  #         enable = true;
  #         settings = {
  #           default_session = {
  #             # Wayland Desktop Manager is installed only for user ryan via home-manager!
  #             user = myvars.noctiere.username;
  #             # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
  #             # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
  #             command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
  #             # command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd $HOME/.wayland-session";  # start wayland session with a TUI login manager
  #           };
  #         };
  #       };
  #     };

  #     # fix https://github.com/ryan4yin/nix-config/issues/10
  #     security.pam.services.swaylock = {};
  #   })
  # ];
}
